# Generated by Django 3.0 on 2023-09-03 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BbApp', '0003_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='apldate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
