# Generated by Django 3.0 on 2023-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BbApp', '0004_requests_apldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='apldate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
