# Generated by Django 3.0 on 2023-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BbApp', '0005_auto_20230903_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
