# Generated by Django 3.0 on 2023-09-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BbApp', '0006_requests_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='Bloodrequests',
        ),
    ]
