# Generated by Django 3.0 on 2023-09-04 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BbApp', '0007_auto_20230903_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=20)),
                ('donor_age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=0)),
                ('apldate', models.DateField(auto_now_add=True)),
                ('diseases', models.CharField(max_length=100)),
                ('dtatus', models.CharField(choices=[('g', 'Pending'), ('a', 'Approved'), ('d', 'Declined')], default='g', max_length=10)),
                ('Med_perdesc', models.CharField(max_length=200)),
                ('don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
